CREATE DATABASE Lab4DB;

USE Lab4DB;

CREATE TABLE students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    roll_no VARCHAR(20) NOT NULL,
    section VARCHAR(10) NOT NULL
);